const FACEBOOK_TOKENS = {
 FACEBOOK_CONSUMER_KEY: process.env.FACEBOOK_CONSUMER_KEY,
 FACEBOOK_CONSUMER_SECRET:process.env.FACEBOOK_CONSUMER_SECRET,
 FACEBOOK_CALLBACK_URL: process.env.FACEBOOK_CALLBACK_URL,
};

const SESSION = {
  COOKIE_KEY: "thisappisawesome"
};

const KEYS = {
  ...FACEBOOK_TOKENS,
  ...SESSION
};

module.exports = KEYS;
