// ADD YOUR OWN KEYS AND RENAME THIS FILE TO keys.js
const FACEBOOK_TOKENS = {
 FACEBOOK_CONSUMER_KEY: "2287506464694314",
 FACEBOOK_CONSUMER_SECRET: "6f056b0e75ff859d433a180321ae1f5c",
 FACEBOOK_ACCESS_TOKEN: "SOME ACCESS TOKEN",
 FACEBOOK_TOKEN_SECRET: "SOME TOKEN SECRET"
};

const SESSION = {
  COOKIE_KEY: "thisappisawesome"
};

const KEYS = {
  ...FACEBOOK_TOKENS,
  ...SESSION
};

module.exports = KEYS;
